travis:
  secure:
    BINSTAR_TOKEN: VnTXaZk30kvlbmYfSkiC/x7bscMNohM5VN6AhiK7rWTYaa7BvX9RuP4/Z7GukiUPMmslgjILtGruuwqF6hD1OoD153yVYJk829FiQ/Hm5rANX9ncKZ5VWo5UgBUB0V4js2CfEwBaOv7q76yGyv5+rdtAMVs0vXxjp/0m1V4047pYsfd9wBhrMUx5IUawkVc+q9HDiMQg8hhVTdvi+XfXs0x/E+pkTAxHcZ17MT78p6WWTgEPNG2xV3j6sG+HKN6AMIl9f/dA/EjA8rzPJczlUypin8gW7Yh559TLNaMTxfNOiyxHJ8RaEC5l/d0CIl1XinKw9UROU3Gvq7Hh4qYXWTS3C/SRUKvtuG9JOOOsDOWfCAH5qAe7h4Fjgpgu3TPkTuXWjI2OGuHZHpBhd4QgSt5f2RubWyuou6qnhsW1L/kI/mI9sZMhHIE1KtsIlmHnjtvr/MC/H6vVpxgQfvK5k+GbkVEw9p2YLb7W7A/sYsBolfT96nlkPW7/Gn6cvHw8TcOd7uUJ9Q5XE7B86fhy6oeJnrvxf0bd4E+b+fup8w2FwSb6gXFFVAnl31J+1SwEyQQPPfmsRplYbmYs8rgtW2Uref6QaHjedQQKJVyVEO0yjVpAKmLjQUn1QWrsjBExdNjN8g6bLqv+jfUkRRs0dQuJiinpXEeqW3SWJx6zVDE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
